name: Run tests

on:
  pull_request:
    branches:
      - ${{ github.event.release.target_commitish }}

jobs:
  run-tests:

    strategy:
      fail-fast: false
      matrix:
        php: [8.2, 8.1]
        os: [ubuntu-latest, windows-latest]

    name: PHP ${{ matrix.php }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, json
          coverage: none

      - name: Setup problem matcher
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: composer update --prefer-dist

      - name: Run tests
        run: vendor/bin/phpunit
